package com.example.priya.listviewcustom;

import android.content.Context;
import android.content.res.Resources;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    ListView list;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        list = (ListView) findViewById(R.id.lv);

        // set adapter
        list.setAdapter(new CustomAdapter(this));
    }
}

class SingleRow{

    String names;
    String phonenos;
    SingleRow(String names, String phonenos){

        this.names=names;
        this.phonenos=phonenos;
    }

}
// class extends baseadapter that implements all methods

class CustomAdapter extends BaseAdapter {
    // Maintain datasource in array
    ArrayList<SingleRow> list2;
    Context context;
    CustomAdapter(Context c){
        context = c;
        list2 = new ArrayList<SingleRow>();
        Resources res = c.getResources();
        String[] names = res.getStringArray(R.array.names);
        String[] phonenos=res.getStringArray(R.array.phonenos);
        for(int i=0;i<6;i++){

            list2.add(new SingleRow(names[i],phonenos[i]));
        }
    }

    @Override
    public int getCount() {
            /*TODO Autogenerated method stub
            returns number of elements inside the array*/

        return list2.size();
    }

    @Override
    public Object getItem(int i) {
            /*TODO Autogenerated method stub
            returns the Object at position arg */
        return list2.get(i);
    }
    @Override
    public long getItemId(int i) {
            /*TODO Autogenerated method stub
            returns id of the row which is the index*/
        return i;
    }
    // getView method to fill the data from array inside the custom struct of the single row for each row
    @Override
    public View getView(int i, View view, ViewGroup viewGroup) {
        //TODO Autogenerated Method

            /*  1.get the root view
                2.use the rootview to find other views
                3.set the values*/

        LayoutInflater inflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);

        //contains a reference to single item linear layout
        View row=inflater.inflate(R.layout.single_item,viewGroup,false);
        TextView name = (TextView) row.findViewById(R.id.tv1);
        TextView phoneno= (TextView)row.findViewById(R.id.tv2);

        SingleRow temp = list2.get(i);

        name.setText(temp.names);
        phoneno.setText(temp.phonenos);
        //return rootView of your single_item.xml
        return row;
    }
}

